const names = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const suffixes = [
  "rulez",
  "king",
  "queen",
  "prince",
  "princess",
  "bamf",
  "poggers",
  "lmao",
  "xd",
  "yum",
  "loser",
  "winner",
  "master",
  "gamer",
  "musician",
  "writer",
  "artist",
  "chef"
]

const thoughts = [
  "I'm not a party animal, but I do like animal parties.",
  "He wondered why at 18 he was old enough to go to war, but not old enough to buy cigarettes.",
  "The paintbrush was angry at the color the artist chose to use.",
  "Today I heard something new and unmemorable.",
  "I never knew what hardship looked like until it started raining bowling balls.",
  "She was the type of girl who wanted to live in a pink house.",
  "On each full moon",
  "She is never happy until she finds something to be unhappy about; then, she is overjoyed.",
  "The thick foliage and intertwined vines made the hike nearly impossible.",
  "The Tsunami wave crashed against the raised houses and broke the pilings as if they were toothpicks.",
  "I’m working on a sweet potato farm.",
  "You can't compare apples and oranges, but what about bananas and plantains?",
  "The estate agent quickly marked out his territory on the dance floor.",
  "The waitress was not amused when he ordered green eggs and ham.",
  "He walked into the basement with the horror movie from the night before playing in his head.",
  "As the asteroid hurtled toward earth, Becky was upset her dentist appointment had been canceled.",
  "Pink horses galloped across the sea.",
  "She had convinced her kids that any mushroom found on the ground would kill them if they touched it.",
  "The pigs were insulted that they were named hamburgers.",
  "He strives to keep the best lawn in the neighborhood.",
  "I would be delighted if the sea were full of cucumber juice.",
  "The best part of marriage is animal crackers with peanut butter.",
  "They did nothing as the raccoon attacked the lady’s bag of food.",
  "Don't step on the broken glass.",
  "Yeah, I think it's a good environment for learning English.",
  "They got there early, and they got really good seats.",
  "She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
  'People keep telling me "orange" but I still prefer "pink".',
  "The sudden rainstorm washed crocodiles into the ocean.",
  "I caught my squirrel rustling through my gym bag.",
  "In that instant, everything changed.",
  "They decided to plant an orchard of cotton candy.",
  "The three-year-old girl ran down the beach as the kite flew behind her.",
  "I currently have 4 windows open up… and I don’t know why.",
  "It was a slippery slope and he was willing to slide all the way to the deepest depths.",
  "One small action would change her life, but whether it would be for better or for worse was yet to be determined.",
  "The best key lime pie is still up for debate.",
  "Peter found road kill an excellent way to save money on dinner.",
  "The doll spun around in circles in hopes of coming alive.",
  "When he had to picnic on the beach, he purposely put sand in other people’s food.",
  "She was disgusted he couldn’t tell the difference between lemonade and limeade.",
  "Purple is the best city in the forest.",
  "When money was tight, he'd get his lunch money from the local wishing well.",
  "As he looked out the window, he saw a clown walk by.",
  "I checked to make sure that he was still alive.",
  "The sight of his goatee made me want to run and hide under my sister-in-law's bed.",
  "It didn't take long for Gary to detect the robbers were amateurs.",
  "He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility.",
  "The glacier came alive as the climbers hiked closer.",
  "The bug was having an excellent day until he hit the windshield."
]

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random full name
const getRandomUsername = () => `${getRandomArrItem(names)}${getRandomArrItem(suffixes)}`;

const getRandomThought = () => `${getRandomArrItem(thoughts)}$`

const generateEmail = (username) => `${username.toLowerCase()}@gmail.com`;

module.exports = { getRandomArrItem, getRandomUsername, getRandomThought, generateEmail };